dist: trusty
sudo: required

language: ruby
cache: bundler

before_script:
  - ./bin/ci/install_on_debian.sh
  - ./bin/ci/before_build.sh

script: "bundle exec rspec"
rvm:
  - jruby-9.1.15.0

notifications:
  recipients:
    - michael@rabbitmq.com

services:
  - rabbitmq

branches:
  only:
    - master
